services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scanner
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      spynet-network:
        ipv4_address: 172.19.0.10
    ports: 
      - "5432:5432"


  scanner:
    build: ./scanner
    networks:
      - spynet-network
    environment:
      - DATABASE_URL=postgresql://username:password123@172.19.0.10:5432/scanner
    cap_add:
      - NET_RAW
      - NET_ADMIN

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password123@db:5432/scanner
    networks:
      - spynet-network
    ports:
      - "5000:5000"

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - spynet-network
    ports:
      - "80:80"

volumes:
  db-data:

networks:
  spynet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
