services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scanner
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spynet-network
    ports: 
      - "5423:5432"

  scanner:
    build: ./scanner
    #network_mode: host
    environment:
      - DATABASE_URL=postgresql://username:password123@db:5432/scanner
    networks: 
      - spynet-network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password123@db:5432/scanner
    networks:
      - spynet-network
    ports:
      - "5000:5000"

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - spynet-network
    ports:
      - "80:80"

volumes:
  db-data:

networks:
  spynet-network:  # Ensure consistent naming
    driver: bridge
