services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scanner
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spynet_default

  scanner:
    build: ./scanner
    network_mode: host
    environment:
      - DATABASE_URL=postgresql://username:password123@localhost:5432/scanner
    networks:
      - host

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password123@db:5432/scanner
    ports:
      - "5000:5000"
    networks:
      - spynet_default

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - spynet_default

volumes:
  db-data:

